config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'users#index' 
  root to: 'users#index'
 
  resources :flashcards

  resources :users

  resources :sessions, only: [:create]
  # get 'welcome', to: 'sessions#welcome'
  get '/login', to: 'sessions#login'
  post 'login', to: 'sessions#create'
  delete "logout", to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flashcard.rb
class Flashcard < ApplicationRecord

    has_many :userflashcards
    has_many :users, through: :userflashcards

    validates :question, presence: true
    validates :content, presence: true

    # scope :public_flashcard, -> {where(public_flashcard: true)}
    # scope :private_flashcard, -> {where(private_flashcard: true)}
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :name, presence: true
    validates :email, presence: true
    validates_uniqueness_of :email

    has_many :userflashcards
    has_many :flashcards, through: :userflashcards
end

app/models/user_flashcard.rb
class UserFlashcard < ApplicationRecord
    belongs_to :user 
    belongs_to :flashcard 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user
    helper_method :logged_in?

    def logged_in?
        !!session[:user_id]
    end
    
    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if !!session[:user_id]
    end
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController

    def index
        @flashcards = Flashcard.all 
    end

    def show
        @flashcard = Flashcard.find(params[:id])
    end

    def new
        @flashcard = Flashcard.new
    end

    def create
        @flashcard = Flashcard.new(flashcard_params)

        if @flashcard.save
            redirect_to flashcards_path
        else
            render 'new'
        end
    end

    def edit
        @flashcard = Flashcard.find(params[:id])
    end

    def update
        @flashcard = Flashcard.find(params[:id])
        @flashcard.update(flashcard_params)
        if @flashcard.save
            redirect_to flashcard_path(@flashcard)
        else
            render 'edit'
        end
    end

    def destroy
        Flashcard.destroy(params[:id])
        redirect_to flashcards_path
    end

    private

    def flashcard_params
        params.require(:flashcard).permit(:question, :content)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create 
        @user = User.find_by(email: params[:email])

        if !!@user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            message = "Invalid email or password"
            redirect_to login_path
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: 'Logged out'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
    end

    def index
        if session[:user_id]
            @user = User.find(session[:user_id])
        end
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render 'new'
        end
    end

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashcards_helper.rb
module FlashcardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/flashcards/edit.html.erb
<h2>Edit Flashcard!</h2>
<%= form_for @flashcard do |f| %>
    <%= f.label :question %>
    <%= f.text_field :question %><br>

    <%= f.label :content %>
    <%= f.text_field :content %><br>

    <%= f.submit %>
<% end %>

app/views/flashcards/index.html.erb
<h1>All the flashcards</h1> 

<%= link_to "Create Flashcard", new_flashcard_path %>
<% @flashcards.each do |flashcard| %>
<ul>
    <li>
        <h2><%= flashcard.question %><br>
        <%= link_to "Answer/View Card", flashcard_path(flashcard) %></h2>
    </li>
</ul>
<% end %>

app/views/flashcards/new.html.erb
<h1>Make a new flashcard!</h1>
<%= form_for @flashcard do |f| %>
    <%= f.label :question %>
    <%= f.text_field :question %><br>

    <%= f.label :content %>
    <%= f.text_field :content %><br>

    <%= f.submit %>
<% end %>
<%= link_to "Show all flashcards", flashcards_path %>

app/views/flashcards/show.html.erb
<h1>Flashcard Question & Answer</h1>

<h3>Question:<br> <%= @flashcard.question %><br><br>
Answer:<br> <%= @flashcard.content %></h3><br>
<%= link_to "Back to Flashcards", flashcards_path %><br>
<%= link_to "Edit Card", edit_flashcard_path(@flashcard) %><br>
<%= link_to "Delete", @flashcard, method: :delete, data: {confirm: "Are you sure you want to delete this card?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuizMeLots</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Quiz-Me-Lots</h1>
<%# #remove whole if statement %>

<% if @user %>
<h1>Welcome: <%= @user.name %></h1><br> 
<% end %>

<%= link_to 'Login', login_path('login') %><br>
<%= link_to 'Create Account', user_path('new') %>

app/views/users/new.html.erb
<h1>Create User Account</h1>

<%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.label :email %>
    <%= f.text_field :email %><br>
    
    <%= f.label :password  %>
    <%= f.password_field :password %><br>

    <%= f.label :password_confirmation  %>
    <%= f.password_field :password_confirmation %><br>

    <%= f.submit %><br>
<% end %>
    

    

app/views/users/show.html.erb
<% if @user %>
<h1>Welcome:<%= @user.name %></h1><br>
<% end %>
<%= button_to"Logout", logout_path, method: "delete" %>